### PR TITLE
Add Commands and Parsers for Meetings, Fix Error Messages for Invalid Commands

### LINKED ISSUE #103: As a busy REA, I want to create meetings
So that I can keep track of my meetings with clients.

### PR DESCRIPTION
**Pull request by Christopher-LM**

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/AddMeetingCommandParser.java [hunk 1]
```diff
@@ -49,14 +47,23 @@ public AddCommand parse(String args) throws ParseException {
...
+        String type = ParserUtil.parseCalendarType(argMultimap.getValue(PREFIX_CALENDAR_TYPE).get());
 
-
-        Name name = ParserUtil.parseName(argMultimap.getValue(PREFIX_NAME).get());
-        Phone phone = ParserUtil.parsePhone(argMultimap.getValue(PREFIX_PHONE).get());
-        Set<Tag> tagList = ParserUtil.parseTags(argMultimap.getAllValues(PREFIX_TAG));
-        Person person = new Person(name, phone, tagList);
-
-        return new AddCommand(person);
+        if (type.contains("p")) {
```
Comment (dianneloh9) [inline src/main/java/seedu/address/logic/parser/AddMeetingCommandParser.java:52]: Can use static variables here, eg `PREFIX_PAPERWORK = "p"`

File: src/main/java/seedu/address/model/calendar/UniqueMeetingList.java [hunk 2]
```diff
@@ -94,7 +93,7 @@ public void setMeetings(seedu.address.model.calendar.UniqueMeetingList replaceme
      */
     public void setMeetings(List<CalendarMeeting> meetings) {
         requireAllNonNull(meetings);
-        if (!propertiesAreUnique(meetings)) {
+        if (!meetingsAreUnique(meetings)) {
```
Comment (dianneloh9) [inline src/main/java/seedu/address/model/calendar/UniqueMeetingList.java:96]: Nice catch

**Review by dianneloh9 — APPROVED** [review]
